[WIP] Feature/cmcd v2 keys
qualabs/dash.js pull request #19
Opened 2024-08-27 18:12 UTC by santiagoqualabs

2024-09-12 19:06 UTC, arrivillagaTomas commented on src/streaming/models/CmcdModel.js
> +
Let's avoid this

2024-09-12 19:06 UTC, arrivillagaTomas commented on src/streaming/models/CmcdModel.js
> -
Let's avoid this

2024-09-12 19:06 UTC, arrivillagaTomas commented on src/streaming/models/CmcdModel.js
> +        if (v === 2) {
Should we use `data.v` ?

2024-09-12 19:06 UTC, arrivillagaTomas commented on test/unit/test/streaming/streaming.models.CmcdModel.js
> +
Let's avoid this

2024-09-12 20:23 UTC, sebastianpiq commented on src/streaming/models/CmcdModel.js
> +        if (v === 2) {
It should be the same value, data.v is set to v in line 524

2024-09-13 14:20 UTC, N1Knight requested changes

2024-09-13 14:20 UTC, N1Knight commented on src/core/Settings.js
> +                        version: null
I think that we should use `version: 1` instead of `version: null`. Defining a variable as null is unnecessary.

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        eventBus.on(MediaPlayerEvents.PLAYBACK_PLAYING, _onPlaybackPlaying, instance)
missing ; at the end of the lines

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +            _playbackStartedTime = Date.now()
missing ; at the end of the line

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +            return
missing ; at the end of the line

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        internalData.msd = Date.now() - _playbackStartedTime
missing ; at the end of the line

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +                const options = _creatCmcdV2HeadersCustomMap()
missing ; at the end of the line

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        let v = settings.get().streaming.cmcd.reporting.requestMode.version ?? DEFAULT_CMCD_VERSION;
Why we are using `let` instead `const` here? 
Also, why we defined another variable instead of assigning it directly to data.v?

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        const cmcdVersion = settings.get().streaming.cmcd.reporting.requestMode.version
missing ; at the end of the line

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        eventBus.off(MediaPlayerEvents.PLAYBACK_PLAYING, _onPlaybackPlaying, instance)
missing ; at the end of the lines

2024-09-13 14:20 UTC, N1Knight commented on src/streaming/models/CmcdModel.js
> +        }
missing ; at the end of the line

2025-01-14 18:25 UTC, nicolaslevy commented
Is this PR deprecated? if true, we should close it

2025-02-27 17:00 UTC, closed without merging