Implement UrlQueryInfo and ExtUrlQueryInfo
qualabs/dash.js pull request #23
Opened 2024-09-04 19:54 UTC by sebastianpiq

2024-09-05 14:28 UTC, arrivillagaTomas commented on src/streaming/controllers/UrlQueryInfoController.js
> +import QueryStrings from '../vo/QureryString.js';
Nombre de archivo QureryString -> queryString

2024-09-05 14:29 UTC, arrivillagaTomas commented on src/streaming/vo/QureryString.js
> +/**
Change file name _QureryString_ -> _QueryString_

2024-09-13 14:26 UTC, N1Knight requested changes

2024-09-13 14:26 UTC, N1Knight commented on src/streaming/controllers/UrlQueryInfoController.js
> +    let instance,
missing ; at the end of the line

2024-09-13 14:26 UTC, N1Knight commented on src/streaming/controllers/UrlQueryInfoController.js
> +        quertStrings = new QueryStrings(mediaInfo)
missing ; at the end of the line

2024-09-13 14:26 UTC, N1Knight commented on src/streaming/controllers/UrlQueryInfoController.js
> +        return request
missing ; at the end of the line

2024-09-13 14:26 UTC, N1Knight commented on src/streaming/controllers/UrlQueryInfoController.js
> +    }
missing ; at the end of the line

2025-02-27 17:00 UTC, closed without merging