[WIP] Implement Alternative MPDs
qualabs/dash.js pull request #24
Opened 2024-09-10 16:01 UTC by sebastianpiq

2024-09-13 14:31 UTC, N1Knight requested changes

2024-09-13 14:31 UTC, N1Knight commented on src/dash/models/DashManifestModel.js
> +
missing ; at the end of multiple lines

2024-09-13 14:31 UTC, N1Knight commented on src/dash/DashAdapter.js
> +            console.log('Linked periods', linkPeriods)
missing ; at the end of the lines

2024-09-13 14:31 UTC, N1Knight commented on src/dash/models/DashManifestModel.js
> +
missing ; at the end of multiple lines

2024-10-09 19:35 UTC, mpollingerQualabs commented on src/dash/models/DashManifestModel.js
> +        return alternativeMpd
```suggestion
        return alternativeMpd;
```

2024-10-09 19:35 UTC, mpollingerQualabs commented on src/dash/constants/DashConstants.js
Shouldn't this file also contain a constant for the alternativeMPD scheme? (`urn:mpeg:dash:event:alternative:2022`)

2024-10-10 16:55 UTC, sebastianpiq commented on src/dash/constants/DashConstants.js
Probably yes. Right now, that scheme is in the streaming constants, but putting it in the DASH ones makes more sense.

2025-01-15 17:04 UTC, closed without merging